apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Values.name }}
  ports:
   - protocol: {{ .Values.protocol }}
     port: {{ .Values.port }}
     targetPort: {{ .Values.targetPort }}
